name: Github Pages

# Cancel any in-progress deployment when a new push comes in
concurrency:
  group: pages-deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout the repo
      - uses: actions/checkout@v3

      # 2) Cache your Ruby gems
      - name: Cache bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # 3) Build & deploy via Jeffrey Tse’s Jekyll action
      - name: Build & Deploy
        uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: github
          token: ${{ secrets.GITHUB_TOKEN }}
          # repository: ''      # (optional) defaults to this repo
          branch: gh-pages
          jekyll_src: ./
          jekyll_cfg: _config.yml
          # jekyll_baseurl: '/jekyll-theme-yat'
          # cname: ''
          # actor: ''
